apiVersion: v1
kind: ServiceAccount
metadata:
  name: service-account
  namespace: hello

---

kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  # namespace: tekton-pipelines
  namespace: hello
  name: pipeline-role
rules:
- apiGroups: ["extensions", "apps", ""]
  resources: ["services", "deployments", "pods", "secrets", "ingresses"]
  verbs: ["get", "create", "update", "patch", "list", "delete", "watch"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pipeline-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pipeline-role
subjects:
- kind: ServiceAccount
  name: service-account
  # namespace: tekton-pipelines
  namespace: hello


---

kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: default
  name: pipeline-cluster-role
rules:
- apiGroups: ["extensions", "apps", ""]
  resources: ["services", "deployments", "pods", "secrets", "ingresses"]
  verbs: ["get", "create", "update", "patch", "list", "delete", "watch"]


---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pipeline-cluster-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pipeline-cluster-role
subjects:
- kind: ServiceAccount
  name: service-account
  namespace: default